-- CRIAR O BANCO DE DADOS
CREATE DATABASE REGISTRO;

-- CRIAR NOSSA TABELA DE PESSOA
CREATE TABLE REGISTRO.PESSOAS(
    ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255)
);